name: Git LFS Pull
description: Prevent Buildkite checkout downloading LFS files and make an explicit call to git lfs pull after checkout
author: https://github.com/triarius
requirements: []
configuration:
  properties: {}
  additionalProperties: false
